import fs from 'node:fs';
import path from 'node:path';

/**
 * Returns Claude Code configuration content for .claude/settings.json.
 *
 * @returns {object}
 */
export function generateClaudeConfig() {
  return {
    hooks: {
      PostToolUseFailure: [
        {
          matcher: 'Bash|PowerShell',
          hooks: [
            {
              name: 'rewind-claude-hook',
              type: 'command',
              command: 'node scripts/rewind-claude-hook.js'
            }
          ]
        }
      ]
    }
  };
}

/**
 * Returns the node script wrapper for bridging Claude Code hooks to `rewind event --json`.
 * Implements strict 5,000ms watchdog timeout and fail-open guarantees.
 *
 * @returns {string}
 */
export function generateClaudeScript() {
  return `#!/usr/bin/env node
// Auto-generated by Rewind (https://github.com/Tejas3479/rewind-cli)
// Claude Code hook bridge (PostToolUseFailure & PreToolUse)
import { spawn } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const TIMEOUT_MS = 5000;

process.on('uncaughtException', (err) => {
  try { process.stderr.write(\`[rewind-bridge:claude] \${err?.message || err}\\n\`); } catch {}
  try { process.stdout.write('{}\\n'); } catch {}
  process.exit(0);
});

let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => { input += chunk; });
process.stdin.on('end', () => {
  try {
    const isWin = process.platform === 'win32';
    const __dirname = path.dirname(fileURLToPath(import.meta.url));
    const localBin = path.resolve(__dirname, '../bin/rewind.js');
    const hasLocalBin = fs.existsSync(localBin);

    let executable = isWin ? 'rewind.cmd' : 'rewind';
    let execArgs = ['event', '--json', '--source', 'claude'];

    if (process.env.REWIND_BIN && fs.existsSync(process.env.REWIND_BIN)) {
      executable = process.env.REWIND_BIN;
    } else if (hasLocalBin) {
      executable = process.execPath;
      execArgs = [localBin, 'event', '--json', '--source', 'claude'];
    }

    const proc = spawn(executable, execArgs, {
      stdio: ['pipe', 'pipe', 'inherit'],
      shell: false
    });

    const timer = setTimeout(() => {
      try { proc.kill('SIGKILL'); } catch {}
      try { process.stderr.write('[rewind-bridge:claude] Watchdog timed out after 5000ms\\n'); } catch {}
      try { process.stdout.write('{}\\n'); } catch {}
      process.exit(0);
    }, TIMEOUT_MS);

    proc.on('error', (err) => {
      clearTimeout(timer);
      try { process.stderr.write(\`[rewind-bridge:claude] \${err?.message || err}\\n\`); } catch {}
      process.stdout.write('{}\\n');
      process.exit(0);
    });

    let output = '';
    proc.stdout.on('data', (d) => { output += d; });
    proc.on('close', () => {
      clearTimeout(timer);
      try {
        const trimmed = output.trim();
        if (!trimmed) {
          process.stdout.write('{}\\n');
          return;
        }
        const parsed = JSON.parse(trimmed);
        if (parsed && parsed.hookSpecificOutput) {
          process.stdout.write(JSON.stringify(parsed) + '\\n');
          return;
        }
        const text = parsed.additionalContext || parsed.additional_context || '';
        if (!text) {
          process.stdout.write('{}\\n');
          return;
        }
        process.stdout.write(JSON.stringify({
          hookSpecificOutput: {
            hookEventName: 'PostToolUseFailure',
            additionalContext: text
          }
        }) + '\\n');
      } catch {
        process.stdout.write('{}\\n');
      }
    });

    proc.stdin.write(input);
    proc.stdin.end();
  } catch {
    process.stdout.write('{}\\n');
    process.exit(0);
  }
});
`;
}

/**
 * Installs Claude Code integration files (.claude/settings.json and scripts/rewind-claude-hook.js).
 *
 * @param {string} rootDir
 * @param {object} [options={}]
 * @param {boolean} [options.dryRun=false]
 * @returns {{ filesCreated: string[] }}
 */
export function installClaudeIntegration(rootDir, options = {}) {
  const claudeDir = path.join(rootDir, '.claude');
  const scriptsDir = path.join(rootDir, 'scripts');
  const settingsPath = path.join(claudeDir, 'settings.json');
  const scriptPath = path.join(scriptsDir, 'rewind-claude-hook.js');

  const filesCreated = [];

  if (!options.dryRun) {
    fs.mkdirSync(claudeDir, { recursive: true });
    fs.mkdirSync(scriptsDir, { recursive: true });

    let existingConfig = {};
    if (fs.existsSync(settingsPath)) {
      try {
        existingConfig = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
      } catch {}
    }

    const hookGroup = [
      {
        matcher: 'Bash|PowerShell',
        hooks: [
          {
            name: 'rewind-claude-hook',
            type: 'command',
            command: 'node scripts/rewind-claude-hook.js'
          }
        ]
      }
    ];

    const merged = {
      ...existingConfig,
      hooks: {
        ...(existingConfig.hooks || {}),
        PostToolUseFailure: hookGroup
      }
    };

    fs.writeFileSync(settingsPath, JSON.stringify(merged, null, 2) + '\n', 'utf8');
    filesCreated.push(settingsPath);

    fs.writeFileSync(scriptPath, generateClaudeScript(), { mode: 0o755 });
    filesCreated.push(scriptPath);
  } else {
    filesCreated.push(settingsPath, scriptPath);
  }

  return { filesCreated };
}
