import fs from 'node:fs';
import path from 'node:path';

/**
 * Returns the recommended .cursor/hooks.json configuration content.
 *
 * @returns {object}
 */
export function generateCursorConfig() {
  return {
    version: 1,
    hooks: {
      postToolUseFailure: [
        {
          command: 'node scripts/rewind-cursor-hook.js',
          timeout: 5
        }
      ]
    }
  };
}

/**
 * Returns the node script wrapper for bridging Cursor hooks to `rewind event --json`.
 *
 * @returns {string}
 */
export function generateCursorScript() {
  return `#!/usr/bin/env node
// Auto-generated by Rewind (https://github.com/Tejas3479/rewind-cli)
// Cursor postToolUseFailure hook bridge
import { spawn } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const TIMEOUT_MS = 5000;

process.on('uncaughtException', (err) => {
  try { process.stderr.write(\`[rewind-bridge:cursor] \${err?.message || err}\\n\`); } catch {}
  try { process.stdout.write('{}\\n'); } catch {}
  process.exit(0);
});

let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => { input += chunk; });
process.stdin.on('end', () => {
  try {
    const isWin = process.platform === 'win32';
    const __dirname = path.dirname(fileURLToPath(import.meta.url));
    const localBin = path.resolve(__dirname, '../bin/rewind.js');
    const hasLocalBin = fs.existsSync(localBin);

    let executable = isWin ? 'rewind.cmd' : 'rewind';
    let execArgs = ['event', '--json', '--source', 'cursor'];

    if (process.env.REWIND_BIN && fs.existsSync(process.env.REWIND_BIN)) {
      executable = process.env.REWIND_BIN;
    } else if (hasLocalBin) {
      executable = process.execPath;
      execArgs = [localBin, 'event', '--json', '--source', 'cursor'];
    }

    const proc = spawn(executable, execArgs, {
      stdio: ['pipe', 'pipe', 'inherit'],
      shell: false
    });

    const timer = setTimeout(() => {
      try { proc.kill('SIGKILL'); } catch {}
      try { process.stderr.write('[rewind-bridge:cursor] Watchdog timed out after 5000ms\\n'); } catch {}
      try { process.stdout.write('{}\\n'); } catch {}
      process.exit(0);
    }, TIMEOUT_MS);

    proc.on('error', (err) => {
      clearTimeout(timer);
      try { process.stderr.write(\`[rewind-bridge:cursor] \${err?.message || err}\\n\`); } catch {}
      process.stdout.write('{}\\n');
      process.exit(0);
    });

    let output = '';
    proc.stdout.on('data', (d) => { output += d; });
    proc.on('close', () => {
      clearTimeout(timer);
      try {
        const trimmed = output.trim();
        if (!trimmed) {
          process.stdout.write('{}\\n');
          return;
        }
        const parsed = JSON.parse(trimmed);
        if (parsed && parsed.additional_context !== undefined) {
          process.stdout.write(JSON.stringify(parsed) + '\\n');
          return;
        }
        const text = parsed.additionalContext || parsed.additional_context || '';
        if (!text) {
          process.stdout.write('{}\\n');
          return;
        }
        process.stdout.write(JSON.stringify({ additional_context: text }) + '\\n');
      } catch {
        process.stdout.write('{}\\n');
      }
    });

    proc.stdin.write(input);
    proc.stdin.end();
  } catch {
    process.stdout.write('{}\\n');
    process.exit(0);
  }
});
`;
}

/**
 * Installs Cursor integration files (.cursor/hooks.json and scripts/rewind-cursor-hook.js).
 *
 * @param {string} rootDir
 * @param {object} [options]
 * @param {boolean} [options.dryRun=false]
 * @returns {{ filesCreated: string[] }}
 */
export function installCursorIntegration(rootDir, options = {}) {
  const cursorDir = path.join(rootDir, '.cursor');
  const scriptsDir = path.join(rootDir, 'scripts');
  const hooksJsonPath = path.join(cursorDir, 'hooks.json');
  const hookScriptPath = path.join(scriptsDir, 'rewind-cursor-hook.js');

  const filesCreated = [];

  if (!options.dryRun) {
    fs.mkdirSync(cursorDir, { recursive: true });
    fs.mkdirSync(scriptsDir, { recursive: true });

    // Merge or create hooks.json
    let existingConfig = {};
    if (fs.existsSync(hooksJsonPath)) {
      try {
        existingConfig = JSON.parse(fs.readFileSync(hooksJsonPath, 'utf8'));
      } catch {}
    }

    const merged = {
      ...existingConfig,
      version: existingConfig.version || 1,
      hooks: {
        ...(existingConfig.hooks || {}),
        postToolUseFailure: [
          {
            command: 'node scripts/rewind-cursor-hook.js',
            timeout: 5
          }
        ]
      }
    };

    fs.writeFileSync(hooksJsonPath, JSON.stringify(merged, null, 2) + '\n', 'utf8');
    filesCreated.push(hooksJsonPath);

    fs.writeFileSync(hookScriptPath, generateCursorScript(), { mode: 0o755 });
    filesCreated.push(hookScriptPath);
  } else {
    filesCreated.push(hooksJsonPath, hookScriptPath);
  }

  return { filesCreated };
}
