import fs from 'node:fs';
import path from 'node:path';

/**
 * Returns the recommended .cursor/hooks.json configuration content.
 *
 * @returns {object}
 */
export function generateCursorConfig() {
  return {
    version: 1,
    hooks: {
      postToolUseFailure: [
        {
          command: 'node scripts/rewind-cursor-hook.js',
          timeout: 5
        }
      ]
    }
  };
}

/**
 * Returns the node script wrapper for bridging Cursor hooks to `rewind event --json`.
 *
 * @returns {string}
 */
export function generateCursorScript() {
  return `#!/usr/bin/env node
// Auto-generated by Rewind (https://github.com/Tejas3479/rewind-cli)
// Cursor postToolUseFailure hook bridge
import { spawn } from 'node:child_process';

let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => { input += chunk; });
process.stdin.on('end', () => {
  const isWin = process.platform === 'win32';
  const bin = isWin ? 'rewind.cmd' : 'rewind';
  const proc = spawn(bin, ['event', '--json'], {
    stdio: ['pipe', 'pipe', 'inherit'],
    shell: true
  });

  let output = '';
  proc.stdout.on('data', (d) => { output += d; });
  proc.on('close', () => {
    try {
      const parsed = JSON.parse(output);
      const text = parsed.additionalContext || parsed.additional_context || '';
      process.stdout.write(JSON.stringify({ additional_context: text }) + '\\n');
    } catch {
      process.stdout.write('{}\\n');
    }
  });

  proc.stdin.write(input);
  proc.stdin.end();
});
`;
}

/**
 * Installs Cursor integration files (.cursor/hooks.json and scripts/rewind-cursor-hook.js).
 *
 * @param {string} rootDir
 * @param {object} [options]
 * @param {boolean} [options.dryRun=false]
 * @returns {{ filesCreated: string[] }}
 */
export function installCursorIntegration(rootDir, options = {}) {
  const cursorDir = path.join(rootDir, '.cursor');
  const scriptsDir = path.join(rootDir, 'scripts');
  const hooksJsonPath = path.join(cursorDir, 'hooks.json');
  const hookScriptPath = path.join(scriptsDir, 'rewind-cursor-hook.js');

  const filesCreated = [];

  if (!options.dryRun) {
    fs.mkdirSync(cursorDir, { recursive: true });
    fs.mkdirSync(scriptsDir, { recursive: true });

    // Merge or create hooks.json
    let existingConfig = {};
    if (fs.existsSync(hooksJsonPath)) {
      try {
        existingConfig = JSON.parse(fs.readFileSync(hooksJsonPath, 'utf8'));
      } catch {}
    }

    const merged = {
      ...existingConfig,
      version: existingConfig.version || 1,
      hooks: {
        ...(existingConfig.hooks || {}),
        postToolUseFailure: [
          {
            command: 'node scripts/rewind-cursor-hook.js',
            timeout: 5
          }
        ]
      }
    };

    fs.writeFileSync(hooksJsonPath, JSON.stringify(merged, null, 2) + '\n', 'utf8');
    filesCreated.push(hooksJsonPath);

    fs.writeFileSync(hookScriptPath, generateCursorScript(), { mode: 0o755 });
    filesCreated.push(hookScriptPath);
  } else {
    filesCreated.push(hooksJsonPath, hookScriptPath);
  }

  return { filesCreated };
}
