import fs from 'node:fs';
import path from 'node:path';

/**
 * Returns Gemini CLI configuration content.
 *
 * @returns {object}
 */
export function generateGeminiConfig() {
  return {
    hooks: {
      AfterTool: [
        {
          matcher: 'run_shell_command',
          hooks: [
            {
              name: 'rewind-gemini-hook',
              type: 'command',
              command: 'node "${GEMINI_PROJECT_DIR:-.}/scripts/rewind-gemini-hook.js"'
            }
          ]
        }
      ]
    }
  };
}

/**
 * Returns the node script wrapper for bridging Gemini CLI hooks to `rewind event --json`.
 *
 * @returns {string}
 */
export function generateGeminiScript() {
  return `#!/usr/bin/env node
// Auto-generated by Rewind (https://github.com/Tejas3479/rewind-cli)
// Gemini CLI AfterTool hook bridge
import { spawn } from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

process.on('uncaughtException', () => {
  try { process.stdout.write('{}\\n'); } catch {}
  process.exit(0);
});

let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => { input += chunk; });
process.stdin.on('end', () => {
  try {
    const isWin = process.platform === 'win32';
    const __dirname = path.dirname(fileURLToPath(import.meta.url));
    const localBin = path.resolve(__dirname, '../bin/rewind.js');
    const hasLocalBin = fs.existsSync(localBin);

    let executable = isWin ? 'rewind.cmd' : 'rewind';
    let execArgs = ['event', '--json'];

    if (process.env.REWIND_BIN && fs.existsSync(process.env.REWIND_BIN)) {
      executable = process.env.REWIND_BIN;
    } else if (hasLocalBin) {
      executable = process.execPath;
      execArgs = [localBin, 'event', '--json'];
    }

    const proc = spawn(executable, execArgs, {
      stdio: ['pipe', 'pipe', 'inherit'],
      shell: false
    });

    proc.on('error', () => {
      process.stdout.write('{}\\n');
      process.exit(0);
    });

    let output = '';
    proc.stdout.on('data', (d) => { output += d; });
    proc.on('close', () => {
      try {
        const parsed = JSON.parse(output);
        const text = parsed.additionalContext || parsed.additional_context || '';
        if (!text) {
          process.stdout.write('{}\\n');
          return;
        }
        process.stdout.write(JSON.stringify({
          hookSpecificOutput: {
            hookEventName: 'AfterTool',
            additionalContext: text
          }
        }) + '\\n');
      } catch {
        process.stdout.write('{}\\n');
      }
    });

    proc.stdin.write(input);
    proc.stdin.end();
  } catch {
    process.stdout.write('{}\\n');
    process.exit(0);
  }
});
`;
}

/**
 * Installs Gemini CLI integration.
 *
 * @param {string} rootDir
 * @param {object} [options]
 * @param {boolean} [options.dryRun=false]
 * @returns {{ filesCreated: string[] }}
 */
export function installGeminiIntegration(rootDir, options = {}) {
  const geminiDir = path.join(rootDir, '.gemini');
  const scriptsDir = path.join(rootDir, 'scripts');
  const settingsPath = path.join(geminiDir, 'settings.json');
  const scriptPath = path.join(scriptsDir, 'rewind-gemini-hook.js');
  const filesCreated = [];

  if (!options.dryRun) {
    fs.mkdirSync(geminiDir, { recursive: true });
    fs.mkdirSync(scriptsDir, { recursive: true });

    let existing = {};
    if (fs.existsSync(settingsPath)) {
      try {
        existing = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
      } catch {}
    }

    const merged = {
      ...existing,
      hooks: {
        ...(existing.hooks || {}),
        AfterTool: [
          {
            matcher: 'run_shell_command',
            hooks: [
              {
                name: 'rewind-gemini-hook',
                type: 'command',
                command: 'node "${GEMINI_PROJECT_DIR:-.}/scripts/rewind-gemini-hook.js"'
              }
            ]
          }
        ]
      }
    };

    fs.writeFileSync(settingsPath, JSON.stringify(merged, null, 2) + '\n', 'utf8');
    filesCreated.push(settingsPath);

    fs.writeFileSync(scriptPath, generateGeminiScript(), { mode: 0o755 });
    filesCreated.push(scriptPath);
  } else {
    filesCreated.push(settingsPath, scriptPath);
  }

  return { filesCreated };
}
